### ISSUE TITLE
output_flexible_layout_blocks not working on single.php templates

### ISSUE THREAD

**Issue by tompha** [wp-buckle/get-go#2]
I have a custom post type with a single template called single-example.php and have added the Page Builder ACF field and have populated it in the backend but  output_flexible_layout_blocks() is not displaying this on the front end. 

Are you able to help debug this please?

**Comment by Vyygir** [comment]
Could you post the code that's in `single-example.php`?

Also, have you created the blocks in `resources/page-builder` so that the function can output the blocks accordingly? If the partials in there don't exist (which should be named as per the block's name in the CMS -- e.g. `content.php`, `column-text.php`, .etc), then the function won't be able to output anything, as it can't find the partials associated with the layout in the CMS to output.

The only other issue I could think of would be the field name for the flexible layout field in the CMS, which should be `page_builder_blocks`. You can see this referenced in the code [here](https://github.com/wp-buckle/get-go/blob/master/functions.php#L33).

I'll keep this open after your issue has been resolved as a note to extend the page block rendering function to support a custom field name.

**Comment by tompha** [comment]
I am so sorry to say but it was another wp_query loop on the page (hidden within a function!) which didn't have a wp_reset_query() and was therefore breaking the page builder plugin loop. Thank you for your response though and will mark as resolved!!!

**Comment by Vyygir** [comment]
@Vyygir Fix common issue in the `output_flexible_layout_blocks` function with the output buffer that sometimes causing a bug in rendering; and allow additional flexibility of changing the field name.
